Vagrant.configure("2") do |config|
    config.vm.define "Containarization" do |web01|
      web01.vm.box = "eurolinux-vagrant/centos-stream-9"
      web01.vm.hostname = "Containarization"
      web01.vm.network "private_network", ip: "192.168.56.45"
    end
 end
  